Description: |
  Creates lambda functions for Reactive LEDs via AWS IoT. https://github.com/rbirkby/aws-infra

Parameters:
  IoTEndpoint:
    Type: String
    Default: a2wkex2gd7mljx.iot.eu-west-1.amazonaws.com
  AlexaApplicationId:
    Type: String
    Default: amzn1.ask.skill.d8c73870-1487-46c0-a715-ba78589f2f31
  IoTCertificate:
    Type: String
    Default: arn:aws:iot:eu-west-1:122053366500:cert/690eaa3ebc8377d8e2c959a3499df4c619b4b3b6b38b55d02906d4a4ca0c66f9

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: reative-leds-service-role
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: write-to-reactive-leds-queue
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Action: iot:Publish
            Resource: !Sub arn:aws:iot:eu-west-1:${AWS::AccountId}:topic/commands

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
         IOT_ENDPOINT: !Ref IoTEndpoint
         ALEXA_APPLICATION: !Ref AlexaApplicationId

      Code:
        ZipFile: >
          'use strict';

          var AWS = require('aws-sdk');
          var iotdata = new AWS.IotData({endpoint: process.env.IOT_ENDPOINT});

          exports.skill = (event, context, callback) => {
              // Prevent unauthorized skills using this lambda function
              if (event.session.application.applicationId !== process.env.ALEXA_APPLICATION) {
                  callback('Invalid Application ID');
              }

              console.log(JSON.stringify(event.request));
              if (event.request.type === "LaunchRequest") {
                  callback(null, {
                      version: "1.0",
                      sessionAttributes: event.session.attributes,
                      response: {
                          outputSpeech: {
                              type: "PlainText",
                              text: 'Which visualization would you like?'
                          },
                          shouldEndSession: false
                      }
                  });                  
              } else if (event.request.type === "IntentRequest" && event.request.intent.name === "VisualizationIntent") {
                  var newVisualization = event.request.intent.slots.Visualization.value;
                  if (['spectrum', 'energy', 'scroll'].indexOf(newVisualization) > -1) {
                      var params = {
                          topic: 'commands',
                          payload: JSON.stringify({message: newVisualization}),
                          qos: 0
                      };

                      // Publish the command via AWS IoT mqtt message queue
                      iotdata.publish(params, (err, data) => {
                          if(err) {
                              console.log(`Unable to switch lights to ${newVisualization}`, err);
                              callback(err)
                          } else {
                              // Respond to the Echo with the results
                              callback(null, {
                                  version: "1.0",
                                  sessionAttributes: event.session.attributes,
                                  response: {
                                      outputSpeech: {
                                          type: "PlainText",
                                          text: `Lights to ${newVisualization}`
                                      },
                                      shouldEndSession: true
                                  }
                              });

                              console.log(`Successfully switched lights to ${newVisualization}`);
                          }
                      });
                  } else {
                      callback(null, {
                          version: "1.0",
                          sessionAttributes: event.session.attributes,
                          response: {
                              outputSpeech: {
                                  type: "PlainText",
                                  text: `Unknown visualization ${newVisualization}`
                              },
                              shouldEndSession: true
                          }
                      });
                      console.log(`Unknown visualization ${newVisualization}`);
                  }
              } else if (event.request.type === "IntentRequest" && event.request.intent.name === 'AMAZON.HelpIntent') {
                  callback(null, {
                      version: "1.0",
                      sessionAttributes: event.session.attributes,
                      response: {
                          outputSpeech: {
                              type: "PlainText",
                              text: `I support 3 visualizations; spectrum, scroll and energy. For example, alexa, ask kitchen lights to show spectrum`
                          },
                          shouldEndSession: true
                      }
                  });
              } else if (event.request.type === "IntentRequest" && event.request.intent.name === "EasterEggIntent") {
                  callback(null, {
                      version: "1.0",
                      sessionAttributes: event.session.attributes,
                      response: {
                          outputSpeech: {
                              type: "SSML",
                              ssml: '<speak><audio src="https://s3-eu-west-1.amazonaws.com/alexa-audio-samples/some+unusual+readings.mp3" /></speak>'
                          },
                          shouldEndSession: true
                      }
                  });
              }
          };

      Description: Connect Alexa to Reactive LEDs
      FunctionName: visualization-skill
      Handler: index.skill
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs4.3
      Timeout: 60

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Lambda
      Action: lambda:InvokeFunction
      Principal: alexa-appkit.amazon.com

  IotDevice:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: ReactiveLeds

  IotDeviceSecurity:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      Principal: !Ref IoTCertificate
      ThingName: !Ref IotDevice

  IotPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Action:
              - iot:Publish
              - iot:Subscribe
              - iot:Connect
              - iot:Receive
          Resource: "*"
          Effect: Allow
      PolicyName: reactiveleds-policy

  IotSecurityPolicy:
    Type: AWS::IoT::PolicyPrincipalAttachment
    Properties:
      Principal: !Ref IoTCertificate
      PolicyName: !Ref IotPolicy
