Description: |
  Creates lambda functions for Reactive LEDs via AWS IoT. https://github.com/rbirkby/aws-infra

Parameters:
  IoTEndpoint:
    Type: String
    Default: a2wkex2gd7mljx.iot.eu-west-1.amazonaws.com
  AlexaApplicationId:
    Type: String
    Default: amzn1.ask.skill.d8c73870-1487-46c0-a715-ba78589f2f31
  IoTCertificate:
    Type: String
    Default: arn:aws:iot:eu-west-1:122053366500:cert/690eaa3ebc8377d8e2c959a3499df4c619b4b3b6b38b55d02906d4a4ca0c66f9

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: reative-leds-service-role
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: write-to-reactive-leds-queue
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Action: iot:Publish
            Resource: !Sub arn:aws:iot:eu-west-1:${AWS::AccountId}:topic/commands

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
         IOT_ENDPOINT: !Ref IoTEndpoint
         ALEXA_APPLICATION: !Ref AlexaApplicationId

      Code:
        ZipFile: >
          'use strict';

          var AWS = require('aws-sdk');
          var iotdata = new AWS.IotData({endpoint: process.env.IOT_ENDPOINT});

          process.on('unhandledRejection', (reason, promise) => {
              console.error('Uncaught error in', promise);
          });

          exports.skill = (event, context, callback) => {
              function startConversation(text) {
                  callback(null, {
                      version: "1.0",
                      sessionAttributes: event.session.attributes,
                      response: {
                          outputSpeech: {
                              type: "PlainText",
                              text: text
                          },
                          shouldEndSession: false
                      }
                  });
              }

              function endConversation(text) {
                  callback(null, {
                      version: "1.0",
                      sessionAttributes: event.session.attributes,
                      response: {
                          outputSpeech: {
                              type: "PlainText",
                              text: text
                          },
                          shouldEndSession: true
                      }
                  });
              }

              function endSsmlConversation(ssml) {
                  callback(null, {
                      version: "1.0",
                      sessionAttributes: event.session.attributes,
                      response: {
                          outputSpeech: {
                              type: "SSML",
                              ssml: ssml
                          },
                          shouldEndSession: true
                      }
                  });
              }

              // Prevent unauthorized skills using this lambda function
              if (event.session.application.applicationId !== process.env.ALEXA_APPLICATION) {
                  callback(new Error('Invalid Application ID'));
              }

              console.log(JSON.stringify(event.request));

              if (event.request.type === "LaunchRequest") {
                  startConversation('Which visualization would you like?');
              } else if (event.request.type === "IntentRequest") {
                  switch(event.request.intent.name) {
                      case "VisualizationIntent":
                          let newVisualization = event.request.intent.slots.Visualization.value;
                          if (['spectrum', 'energy', 'scroll'].indexOf(newVisualization) > -1) {
                              var params = {
                                  topic: 'commands',
                                  payload: JSON.stringify({message: newVisualization}),
                                  qos: 0
                              };

                              // Publish the command via AWS IoT mqtt message queue
                              iotdata.publish(params).promise()
                                  .then(data => {
                                      // Respond to the Echo with the results
                                      endConversation(`Lights to ${newVisualization}`);

                                      console.log(`Successfully switched lights to ${newVisualization}`);
                                  }).catch(err => {
                                      console.error(`Error publishing command to IoT. Unable to switch lights to ${newVisualization}`, err);
                                      callback(err);
                                  });
                          } else if (newVisualization) {
                              startConversation('I only support spectrum, scroll and energy. Which would you like?');
                              console.log(`Unknown visualization ${newVisualization}`);
                          } else {
                              startConversation('Which visualization was that?');
                          }
                          break;
                      case "AMAZON.HelpIntent":
                          startConversation(`I support 3 visualizations; spectrum, scroll and energy. For example, alexa, ask kitchen lights to show spectrum. Which visualization would you like?`);
                          break;
                      case "EasterEggIntent":
                          endSsmlConversation('<speak><audio src="https://s3-eu-west-1.amazonaws.com/alexa-audio-samples/some+unusual+readings.mp3" /></speak>');
                          break;
                      default:
                          startConversation('Which visualization would you like?');
                          break;
                  }
              }
          };

      Description: Connect Alexa to Reactive LEDs
      FunctionName: visualization-skill
      Handler: index.skill
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs4.3
      Timeout: 60

  # Give permission to Alexa (*any skill*) to invoke this lambda function
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Lambda
      Action: lambda:InvokeFunction
      Principal: alexa-appkit.amazon.com

  IoTDevice:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: ReactiveLeds

  IoTDeviceSecurity:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      Principal: !Ref IoTCertificate
      ThingName: !Ref IoTDevice

  IoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Action:
              - iot:Publish
              - iot:Subscribe
              - iot:Connect
              - iot:Receive
          Resource: "*"
          Effect: Allow
      PolicyName: reactiveleds-policy

  IotSecurityPolicy:
    Type: AWS::IoT::PolicyPrincipalAttachment
    Properties:
      Principal: !Ref IoTCertificate
      PolicyName: !Ref IoTPolicy
