Description: |
  Creates lambda functions for iot. https://github.com/rbirkby/aws-infra

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: reative-leds-service-role
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: write-to-reactive-leds-queue
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Action: iot:Publish
            Resource: "arn:aws:iot:eu-west-1:122053366500:topic/commands"

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: >
          'use strict';

          var AWS = require('aws-sdk');
          var iotdata = new AWS.IotData({endpoint: 'a2wkex2gd7mljx.iot.eu-west-1.amazonaws.com'});

          exports.skill = (event, context, callback) => {
              var params = {
                  topic: 'commands',
                  payload: JSON.stringify({message: event.request.intent.slots.Visualization.value}),
                  qos: 0
              };

              iotdata.publish(params, (err, data) => {
                  if(err) {
                      console.log(err);
                  } else {
                      callback(null, {
                          version: "1.0",
                          sessionAttributes: event.session.attributes,
                          response: {
                              outputSpeech: {
                                  type: "PlainText",
                                  text: "Lights to " + JSON.stringify(event.request.intent.slots.Visualization.value)
                              },
                              shouldEndSession: true
                          }
                      });

                      console.log("success");
                      context.succeed(event);
                  }
              });
          };


      Description: Connect Alexa to Reactive LEDs
      FunctionName: visualization-skill
      Handler: index.skill
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs4.3
      Timeout: 60

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Lambda
      Action: lambda:InvokeFunction
      Principal: alexa-appkit.amazon.com
