Description: |
  AWS CodePipeline for deploying CloudFormation templates. https://github.com/rbirkby/aws-infra

Parameters:
  GitHubToken: 
    Type: String
    Description: GitHub OAuth Personal Access Token with admin:repo_hook and repo scopes

Resources:
  DummyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: codepipeline-dummy-artifactstore
      Tags:
        - {Key: environment, Value: prod}  

  CloudFormationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudformation-service-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
          Action: sts:AssumeRole

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: codepipeline-service-role
      Policies:
      - PolicyName: codepipeline-policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Action:
            - s3:*
            - sns:*
            - cloudformation:*
            - iam:PassRole
            Resource: "*"
            Effect: Allow
          - Action:
            - lambda:InvokeFunction
            - lambda:ListFunctions
            Resource: "*"
            Effect: Allow
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      Name: stack-builder
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      Stages: 
        - Name: Source
          Actions: 
            - Name: SourceAction
              ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts: 
                - Name: SourceTree
              Configuration: 
                Owner: rbirkby
                Repo: aws-infra
                Branch: master
                OAuthToken: !Ref GitHubToken
        - Name: infrastructure-builder
          Actions: 
            - Name: vpc
              InputArtifacts: 
                - Name: SourceTree
              ActionTypeId: 
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration: 
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CloudFormationServiceRole.Arn
                StackName: vpc 
                TemplatePath: SourceTree::vpc.yaml
            - Name: zimicats
              InputArtifacts: 
                - Name: SourceTree
              ActionTypeId: 
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration: 
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CloudFormationServiceRole.Arn
                StackName: zimicats
                TemplatePath: SourceTree::zimicats.yaml 
                Capabilities: CAPABILITY_NAMED_IAM 
            - Name: iot
              InputArtifacts: 
                - Name: SourceTree
              ActionTypeId: 
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration: 
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CloudFormationServiceRole.Arn
                StackName: iot 
                TemplatePath: SourceTree::iot.yaml                
      ArtifactStore: 
        Type: S3
        Location: !Ref DummyBucket
