Description: |
  Simple VPC to prove CloudFormation stack. https://github.com/rbirkby/aws-infra

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.20.0.0/16
      Tags:
        - {Key: Name, Value: TestVPC}
        - {Key: environment, Value: dev}  
