Description: |
  Simple VPC to prove CloudFormation stack

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - {Key: Name, Value: TestVPC}
        - {Key: environment, Value: dev}  
