Description: |
  Backs up the zimicats and timetomine server. https://github.com/rbirkby/aws-infra

Parameters:
  BucketName:
    Type: String
    Default: zimicats-minecraft-backup

Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: zimicats-minecraft
      Policies:
      - PolicyName: write-to-backup-bucket
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Action:
                - "s3:PutObject"
                - "s3:ListBucket"
                - "s3:ListObjects"
            Resource:
                - !Sub "arn:aws:s3:::${Bucket}/*"
                - !Sub "arn:aws:s3:::${Bucket}"
            Effect: Allow
            Sid: PermissionForObjectOperations

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
        - Id: transition-to-infrequent-access
          Status: Enabled
          Transitions:
          - StorageClass: STANDARD_IA
            TransitionInDays: 30
      Tags:
        - {Key: environment, Value: prodX}

  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref User

Outputs:
  AccessKey:
    Value: !Ref AccessKey
  SecretKey:
    Value: !GetAtt AccessKey.SecretAccessKey
